<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="green">
        <color rgba="0 0.6 0 1" />
    </material>
    
    <material name="gray">
    <color rgba="0.7 0.7 0.7 1" />
</material>

<xacro:property name="base_length" value="0.6" />
<xacro:property name="base_width" value="0.4" />
<xacro:property name="base_height" value="0.2" />
<xacro:property name="wheel_radius" value="0.1" />
<xacro:property name="wheel_length" value="0.05" />
    
    <link name="base_link">
        <visual>
          <geometry>
           <box size="${base_length} ${base_width} ${base_height}" />
          </geometry>
          <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
          <material name="green" />
        </visual>
    </link>
    
	 <!--  <link name="shoulder_link">
	      <visual>
	         <geometry>
                  <cylinder radius="0.2" length="0.5"/>
              </geometry>
            <origin xyz="0 0 0" rpy="0.35 0 0" />
               <material name="gray" />
	        </visual>
	    </link> -->


 

  <!--     
	 <joint name="base_shoulder_joint" type="revolute">
		    <parent link="base_link" />
		    <child link="shoulder_link" />
		    <origin xyz="0 0 0.15" rpy="0 0 0" />
		    <axis xyz="0 0 1" />
		    <limit lower="-3.14" upper="3.14" velocity="100" effort="100"/>
       </joint> -->

	<link name="right_wheel_link">
	    <visual>
	        <geometry>
	            <cylinder radius="0.1" length="0.05" />
	        </geometry>
	        <origin xyz="0 0 0" rpy="1.57 0 0" />
	        <material name="gray" />
	    </visual>
	</link>
		
	 <joint name="base_right_wheel_joint" type="continuous">
	    <parent link="base_link" />
	    <child link="right_wheel_link" />
	 <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) /
2.0} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
	</joint>
	
		
	<link name="left_wheel_link">
	    <visual>
	        <geometry>
	            <cylinder radius="0.1" length="0.05" />
	        </geometry>
	        <origin xyz="0 0 0" rpy="1.57 0 0" />
	        <material name="gray" />
	    </visual>
	</link>

	<joint name="base_left_wheel_joint" type="continuous">
	    <parent link="base_link" />
	    <child link="left_wheel_link" />
	    <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
	     <axis xyz="0 1 0" />
	</joint>
	
	<link name="caster_wheel_link">
	    <visual>
	     <geometry>
		    <sphere radius="${wheel_radius / 2.0}" />
		 </geometry>
	   	 <origin xyz="0 0 0" rpy="0 0 0" />
	     <material name="gray" />
	    </visual>
	</link>

	<joint name="base_caster_wheel_joint" type="fixed">
	    <parent link="base_link" />
	    <child link="caster_wheel_link" />
	    <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
	</joint>
	
	<link name="base_footprint" />
	
	
	<joint name="base_joint" type="fixed">
	    <parent link="base_footprint" />
	    <child link="base_link" />
	    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />  
	</joint>
</robot>
